//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AW.LLBLGen.DataContextDriver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AdditionalAssemblies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdditionalAssemblies"]));
            }
            set {
                this["AdditionalAssemblies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AdditionalNamespaces {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdditionalNamespaces"]));
            }
            set {
                this["AdditionalNamespaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDataAccessAdapterFactoryMethod {
            get {
                return ((string)(this["DefaultDataAccessAdapterFactoryMethod"]));
            }
            set {
                this["DefaultDataAccessAdapterFactoryMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDataAccessAdapterFactoryType {
            get {
                return ((string)(this["DefaultDataAccessAdapterFactoryType"]));
            }
            set {
                this["DefaultDataAccessAdapterFactoryType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultLinqMetaData {
            get {
                return ((string)(this["DefaultLinqMetaData"]));
            }
            set {
                this["DefaultLinqMetaData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultLinqMetaDataAssembly {
            get {
                return ((string)(this["DefaultLinqMetaDataAssembly"]));
            }
            set {
                this["DefaultLinqMetaDataAssembly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultApplicationConfig {
            get {
                return ((string)(this["DefaultApplicationConfig"]));
            }
            set {
                this["DefaultApplicationConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDataAccessAdapterFactoryAssembly {
            get {
                return ((string)(this["DefaultDataAccessAdapterFactoryAssembly"]));
            }
            set {
                this["DefaultDataAccessAdapterFactoryAssembly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDatabaseConnection {
            get {
                return ((string)(this["DefaultDatabaseConnection"]));
            }
            set {
                this["DefaultDatabaseConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDisplayName {
            get {
                return ((string)(this["DefaultDisplayName"]));
            }
            set {
                this["DefaultDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionDialogPlacement {
            get {
                return ((string)(this["ConnectionDialogPlacement"]));
            }
            set {
                this["ConnectionDialogPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultAdapterAssembly {
            get {
                return ((string)(this["DefaultAdapterAssembly"]));
            }
            set {
                this["DefaultAdapterAssembly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultAdapterType {
            get {
                return ((string)(this["DefaultAdapterType"]));
            }
            set {
                this["DefaultAdapterType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultConnectionType {
            get {
                return ((int)(this["DefaultConnectionType"]));
            }
            set {
                this["DefaultConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultProvider {
            get {
                return ((string)(this["DefaultProvider"]));
            }
            set {
                this["DefaultProvider"] = value;
            }
        }
    }
}
