xcopy /y  bin\debug\AW.DebugVisualizers.* "%userprofile%\My Documents\Visual Studio 2010\Visualizers"
xcopy /y  bin\debug\AW.Helper.* "%userprofile%\My Documents\Visual Studio 2010\Visualizers"
xcopy /y  bin\debug\AW.Winforms.Helpers.* "%userprofile%\My Documents\Visual Studio 2010\Visualizers"
xcopy /y  bin\debug\Dynamic.* "%userprofile%\My Documents\Visual Studio 2010\Visualizers"
xcopy /y  bin\debug\ObjectListView.* "%userprofile%\My Documents\Visual Studio 2010\Visualizers"