//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AW.Winforms.Helpers.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle EntityViewerSizeLocation {
            get {
                return ((global::System.Drawing.Rectangle)(this["EntityViewerSizeLocation"]));
            }
            set {
                this["EntityViewerSizeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EntityFieldColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EntityFieldColumns"]));
            }
            set {
                this["EntityFieldColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("462")]
        public int FrmEntityViewerSplitterDistance {
            get {
                return ((int)(this["FrmEntityViewerSplitterDistance"]));
            }
            set {
                this["FrmEntityViewerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle QueryRunnerSizeAndLocation {
            get {
                return ((global::System.Drawing.Rectangle)(this["QueryRunnerSizeAndLocation"]));
            }
            set {
                this["QueryRunnerSizeAndLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDataTypes {
            get {
                return ((bool)(this["ShowDataTypes"]));
            }
            set {
                this["ShowDataTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNonPublicMembers {
            get {
                return ((bool)(this["ShowNonPublicMembers"]));
            }
            set {
                this["ShowNonPublicMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowStaticMembers {
            get {
                return ((bool)(this["ShowStaticMembers"]));
            }
            set {
                this["ShowStaticMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle EntitiesAndFieldsSizeLocation {
            get {
                return ((global::System.Drawing.Rectangle)(this["EntitiesAndFieldsSizeLocation"]));
            }
            set {
                this["EntitiesAndFieldsSizeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle DataEditorSizeLocation {
            get {
                return ((global::System.Drawing.Rectangle)(this["DataEditorSizeLocation"]));
            }
            set {
                this["DataEditorSizeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle HierarchyEditorSizeLocation {
            get {
                return ((global::System.Drawing.Rectangle)(this["HierarchyEditorSizeLocation"]));
            }
            set {
                this["HierarchyEditorSizeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropertiesToExclude {
            get {
                return ((string)(this["PropertiesToExclude"]));
            }
            set {
                this["PropertiesToExclude"] = value;
            }
        }
    }
}
