//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 1/09/2014 4:34:53 p.m.

using Northwind.DAL.EntityClasses;

namespace Northwind.Win.NorthwindODataSRSharedTypes
{
    
    /// <summary>
    /// There are no comments for LLBLGenProODataService in the schema.
    /// </summary>
    public partial class LLBLGenProODataService : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new LLBLGenProODataService object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LLBLGenProODataService(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Northwind.DAL.EntityClasses", "Northwind.Win.NorthwindODataSRSharedTypes");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Northwind.Win.NorthwindODataSRSharedTypes", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Northwind.DAL.EntityClasses.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CategoryEntity> Category
        {
            get
            {
                if ((this._Category == null))
                {
                    this._Category = base.CreateQuery<CategoryEntity>("Category");
                }
                return this._Category;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CategoryEntity> _Category;
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CustomerEntity> Customer
        {
            get
            {
                if ((this._Customer == null))
                {
                    this._Customer = base.CreateQuery<CustomerEntity>("Customer");
                }
                return this._Customer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CustomerEntity> _Customer;
        /// <summary>
        /// There are no comments for CustomerCustomerDemo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CustomerCustomerDemoEntity> CustomerCustomerDemo
        {
            get
            {
                if ((this._CustomerCustomerDemo == null))
                {
                    this._CustomerCustomerDemo = base.CreateQuery<CustomerCustomerDemoEntity>("CustomerCustomerDemo");
                }
                return this._CustomerCustomerDemo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CustomerCustomerDemoEntity> _CustomerCustomerDemo;
        /// <summary>
        /// There are no comments for CustomerDemographic in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CustomerDemographicEntity> CustomerDemographic
        {
            get
            {
                if ((this._CustomerDemographic == null))
                {
                    this._CustomerDemographic = base.CreateQuery<CustomerDemographicEntity>("CustomerDemographic");
                }
                return this._CustomerDemographic;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CustomerDemographicEntity> _CustomerDemographic;
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EmployeeEntity> Employee
        {
            get
            {
                if ((this._Employee == null))
                {
                    this._Employee = base.CreateQuery<EmployeeEntity>("Employee");
                }
                return this._Employee;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EmployeeEntity> _Employee;
        /// <summary>
        /// There are no comments for EmployeeTerritory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EmployeeTerritoryEntity> EmployeeTerritory
        {
            get
            {
                if ((this._EmployeeTerritory == null))
                {
                    this._EmployeeTerritory = base.CreateQuery<EmployeeTerritoryEntity>("EmployeeTerritory");
                }
                return this._EmployeeTerritory;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EmployeeTerritoryEntity> _EmployeeTerritory;
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrderEntity> Order
        {
            get
            {
                if ((this._Order == null))
                {
                    this._Order = base.CreateQuery<OrderEntity>("Order");
                }
                return this._Order;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrderEntity> _Order;
        /// <summary>
        /// There are no comments for OrderDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrderDetailEntity> OrderDetail
        {
            get
            {
                if ((this._OrderDetail == null))
                {
                    this._OrderDetail = base.CreateQuery<OrderDetailEntity>("OrderDetail");
                }
                return this._OrderDetail;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrderDetailEntity> _OrderDetail;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ProductEntity> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<ProductEntity>("Product");
                }
                return this._Product;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ProductEntity> _Product;
        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RegionEntity> Region
        {
            get
            {
                if ((this._Region == null))
                {
                    this._Region = base.CreateQuery<RegionEntity>("Region");
                }
                return this._Region;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RegionEntity> _Region;
        /// <summary>
        /// There are no comments for Shipper in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ShipperEntity> Shipper
        {
            get
            {
                if ((this._Shipper == null))
                {
                    this._Shipper = base.CreateQuery<ShipperEntity>("Shipper");
                }
                return this._Shipper;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ShipperEntity> _Shipper;
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SupplierEntity> Supplier
        {
            get
            {
                if ((this._Supplier == null))
                {
                    this._Supplier = base.CreateQuery<SupplierEntity>("Supplier");
                }
                return this._Supplier;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SupplierEntity> _Supplier;
        /// <summary>
        /// There are no comments for Territory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TerritoryEntity> Territory
        {
            get
            {
                if ((this._Territory == null))
                {
                    this._Territory = base.CreateQuery<TerritoryEntity>("Territory");
                }
                return this._Territory;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TerritoryEntity> _Territory;
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCategory(CategoryEntity categoryEntity)
        {
            base.AddObject("Category", categoryEntity);
        }
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomer(CustomerEntity customerEntity)
        {
            base.AddObject("Customer", customerEntity);
        }
        /// <summary>
        /// There are no comments for CustomerCustomerDemo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomerCustomerDemo(CustomerCustomerDemoEntity customerCustomerDemoEntity)
        {
            base.AddObject("CustomerCustomerDemo", customerCustomerDemoEntity);
        }
        /// <summary>
        /// There are no comments for CustomerDemographic in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomerDemographic(CustomerDemographicEntity customerDemographicEntity)
        {
            base.AddObject("CustomerDemographic", customerDemographicEntity);
        }
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEmployee(EmployeeEntity employeeEntity)
        {
            base.AddObject("Employee", employeeEntity);
        }
        /// <summary>
        /// There are no comments for EmployeeTerritory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEmployeeTerritory(EmployeeTerritoryEntity employeeTerritoryEntity)
        {
            base.AddObject("EmployeeTerritory", employeeTerritoryEntity);
        }
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrder(OrderEntity orderEntity)
        {
            base.AddObject("Order", orderEntity);
        }
        /// <summary>
        /// There are no comments for OrderDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrderDetail(OrderDetailEntity orderDetailEntity)
        {
            base.AddObject("OrderDetail", orderDetailEntity);
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProduct(ProductEntity productEntity)
        {
            base.AddObject("Product", productEntity);
        }
        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRegion(RegionEntity regionEntity)
        {
            base.AddObject("Region", regionEntity);
        }
        /// <summary>
        /// There are no comments for Shipper in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToShipper(ShipperEntity shipperEntity)
        {
            base.AddObject("Shipper", shipperEntity);
        }
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSupplier(SupplierEntity supplierEntity)
        {
            base.AddObject("Supplier", supplierEntity);
        }
        /// <summary>
        /// There are no comments for Territory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTerritory(TerritoryEntity territoryEntity)
        {
            base.AddObject("Territory", territoryEntity);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Northwind.DAL.EntityClasses\" xmlns=\"http://schemas.microsoft.com/ado/" +
                "2007/05/edm\"><EntityType Name=\"CategoryEntity\"><Key><PropertyRef Name=\"CategoryI" +
                "d\" /></Key><Property Name=\"CategoryId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Prop" +
                "erty Name=\"CategoryName\" Type=\"Edm.String\" /><Property Name=\"Description\" Type=\"" +
                "Edm.String\" /><Property Name=\"Picture\" Type=\"Edm.Binary\" /><NavigationProperty N" +
                "ame=\"Products\" Relationship=\"Northwind.DAL.EntityClasses.CategoryEntity_Products" +
                "_ProductEntity_Category\" ToRole=\"ProductEntity_Category\" FromRole=\"CategoryEntit" +
                "y_Products\" /></EntityType><EntityType Name=\"CustomerEntity\"><Key><PropertyRef N" +
                "ame=\"CustomerId\" /></Key><Property Name=\"Address\" Type=\"Edm.String\" /><Property " +
                "Name=\"City\" Type=\"Edm.String\" /><Property Name=\"CompanyName\" Type=\"Edm.String\" /" +
                "><Property Name=\"ContactName\" Type=\"Edm.String\" /><Property Name=\"ContactTitle\" " +
                "Type=\"Edm.String\" /><Property Name=\"Country\" Type=\"Edm.String\" /><Property Name=" +
                "\"CustomerId\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Fax\" Type=\"Edm" +
                ".String\" /><Property Name=\"Phone\" Type=\"Edm.String\" /><Property Name=\"PostalCode" +
                "\" Type=\"Edm.String\" /><Property Name=\"Region\" Type=\"Edm.String\" /><NavigationPro" +
                "perty Name=\"CustomerCustomerDemos\" Relationship=\"Northwind.DAL.EntityClasses.Cus" +
                "tomerEntity_CustomerCustomerDemos_CustomerCustomerDemoEntity_Customer\" ToRole=\"C" +
                "ustomerCustomerDemoEntity_Customer\" FromRole=\"CustomerEntity_CustomerCustomerDem" +
                "os\" /><NavigationProperty Name=\"Orders\" Relationship=\"Northwind.DAL.EntityClasse" +
                "s.CustomerEntity_Orders_OrderEntity_Customer\" ToRole=\"OrderEntity_Customer\" From" +
                "Role=\"CustomerEntity_Orders\" /><NavigationProperty Name=\"CustomerDemographics\" R" +
                "elationship=\"Northwind.DAL.EntityClasses.CustomerEntity_CustomerDemographics\" To" +
                "Role=\"CustomerDemographics\" FromRole=\"CustomerEntity\" /><NavigationProperty Name" +
                "=\"EmployeesViaOrders\" Relationship=\"Northwind.DAL.EntityClasses.CustomerEntity_E" +
                "mployeesViaOrders\" ToRole=\"EmployeesViaOrders\" FromRole=\"CustomerEntity\" /></Ent" +
                "ityType><EntityType Name=\"CustomerCustomerDemoEntity\"><Key><PropertyRef Name=\"Cu" +
                "stomerId\" /><PropertyRef Name=\"CustomerTypeId\" /></Key><Property Name=\"CustomerI" +
                "d\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"CustomerTypeId\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" /><NavigationProperty Name=\"Customer\" Relationship=\"N" +
                "orthwind.DAL.EntityClasses.CustomerEntity_CustomerCustomerDemos_CustomerCustomer" +
                "DemoEntity_Customer\" ToRole=\"CustomerEntity_CustomerCustomerDemos\" FromRole=\"Cus" +
                "tomerCustomerDemoEntity_Customer\" /><NavigationProperty Name=\"CustomerDemographi" +
                "c\" Relationship=\"Northwind.DAL.EntityClasses.CustomerCustomerDemoEntity_Customer" +
                "Demographic_CustomerDemographicEntity_CustomerCustomerDemos\" ToRole=\"CustomerDem" +
                "ographicEntity_CustomerCustomerDemos\" FromRole=\"CustomerCustomerDemoEntity_Custo" +
                "merDemographic\" /></EntityType><EntityType Name=\"CustomerDemographicEntity\"><Key" +
                "><PropertyRef Name=\"CustomerTypeId\" /></Key><Property Name=\"CustomerDesc\" Type=\"" +
                "Edm.String\" /><Property Name=\"CustomerTypeId\" Type=\"Edm.String\" Nullable=\"false\"" +
                " /><NavigationProperty Name=\"CustomerCustomerDemos\" Relationship=\"Northwind.DAL." +
                "EntityClasses.CustomerCustomerDemoEntity_CustomerDemographic_CustomerDemographic" +
                "Entity_CustomerCustomerDemos\" ToRole=\"CustomerCustomerDemoEntity_CustomerDemogra" +
                "phic\" FromRole=\"CustomerDemographicEntity_CustomerCustomerDemos\" /><NavigationPr" +
                "operty Name=\"Customers\" Relationship=\"Northwind.DAL.EntityClasses.CustomerDemogr" +
                "aphicEntity_Customers\" ToRole=\"Customers\" FromRole=\"CustomerDemographicEntity\" /" +
                "></EntityType><EntityType Name=\"EmployeeEntity\"><Key><PropertyRef Name=\"Employee" +
                "Id\" /></Key><Property Name=\"Address\" Type=\"Edm.String\" /><Property Name=\"BirthDa" +
                "te\" Type=\"Edm.DateTime\" /><Property Name=\"City\" Type=\"Edm.String\" /><Property Na" +
                "me=\"Country\" Type=\"Edm.String\" /><Property Name=\"EmployeeId\" Type=\"Edm.Int32\" Nu" +
                "llable=\"false\" /><Property Name=\"Extension\" Type=\"Edm.String\" /><Property Name=\"" +
                "FirstName\" Type=\"Edm.String\" /><Property Name=\"HireDate\" Type=\"Edm.DateTime\" /><" +
                "Property Name=\"HomePhone\" Type=\"Edm.String\" /><Property Name=\"LastName\" Type=\"Ed" +
                "m.String\" /><Property Name=\"Notes\" Type=\"Edm.String\" /><Property Name=\"Photo\" Ty" +
                "pe=\"Edm.Binary\" /><Property Name=\"PhotoPath\" Type=\"Edm.String\" /><Property Name=" +
                "\"PostalCode\" Type=\"Edm.String\" /><Property Name=\"Region\" Type=\"Edm.String\" /><Pr" +
                "operty Name=\"ReportsTo\" Type=\"Edm.Int32\" /><Property Name=\"Title\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"TitleOfCourtesy\" Type=\"Edm.String\" /><NavigationProperty N" +
                "ame=\"Staff\" Relationship=\"Northwind.DAL.EntityClasses.EmployeeEntity_Staff_Emplo" +
                "yeeEntity_Manager\" ToRole=\"EmployeeEntity_Manager\" FromRole=\"EmployeeEntity_Staf" +
                "f\" /><NavigationProperty Name=\"EmployeeTerritories\" Relationship=\"Northwind.DAL." +
                "EntityClasses.EmployeeEntity_EmployeeTerritories_EmployeeTerritoryEntity_Employe" +
                "e\" ToRole=\"EmployeeTerritoryEntity_Employee\" FromRole=\"EmployeeEntity_EmployeeTe" +
                "rritories\" /><NavigationProperty Name=\"Orders\" Relationship=\"Northwind.DAL.Entit" +
                "yClasses.EmployeeEntity_Orders_OrderEntity_Employee\" ToRole=\"OrderEntity_Employe" +
                "e\" FromRole=\"EmployeeEntity_Orders\" /><NavigationProperty Name=\"CustomersViaOrde" +
                "rs\" Relationship=\"Northwind.DAL.EntityClasses.EmployeeEntity_CustomersViaOrders\"" +
                " ToRole=\"CustomersViaOrders\" FromRole=\"EmployeeEntity\" /><NavigationProperty Nam" +
                "e=\"Territories\" Relationship=\"Northwind.DAL.EntityClasses.EmployeeEntity_Territo" +
                "ries\" ToRole=\"Territories\" FromRole=\"EmployeeEntity\" /><NavigationProperty Name=" +
                "\"Manager\" Relationship=\"Northwind.DAL.EntityClasses.EmployeeEntity_Staff_Employe" +
                "eEntity_Manager\" ToRole=\"EmployeeEntity_Staff\" FromRole=\"EmployeeEntity_Manager\"" +
                " /></EntityType><EntityType Name=\"EmployeeTerritoryEntity\"><Key><PropertyRef Nam" +
                "e=\"EmployeeId\" /><PropertyRef Name=\"TerritoryId\" /></Key><Property Name=\"Employe" +
                "eId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"TerritoryId\" Type=\"Edm." +
                "String\" Nullable=\"false\" /><NavigationProperty Name=\"Employee\" Relationship=\"Nor" +
                "thwind.DAL.EntityClasses.EmployeeEntity_EmployeeTerritories_EmployeeTerritoryEnt" +
                "ity_Employee\" ToRole=\"EmployeeEntity_EmployeeTerritories\" FromRole=\"EmployeeTerr" +
                "itoryEntity_Employee\" /><NavigationProperty Name=\"Territory\" Relationship=\"North" +
                "wind.DAL.EntityClasses.EmployeeTerritoryEntity_Territory_TerritoryEntity_Employe" +
                "eTerritories\" ToRole=\"TerritoryEntity_EmployeeTerritories\" FromRole=\"EmployeeTer" +
                "ritoryEntity_Territory\" /></EntityType><EntityType Name=\"OrderEntity\"><Key><Prop" +
                "ertyRef Name=\"OrderId\" /></Key><Property Name=\"CustomerId\" Type=\"Edm.String\" /><" +
                "Property Name=\"EmployeeId\" Type=\"Edm.Int32\" /><Property Name=\"Freight\" Type=\"Edm" +
                ".Decimal\" /><Property Name=\"OrderDate\" Type=\"Edm.DateTime\" /><Property Name=\"Ord" +
                "erId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"RequiredDate\" Type=\"Ed" +
                "m.DateTime\" /><Property Name=\"ShipAddress\" Type=\"Edm.String\" /><Property Name=\"S" +
                "hipCity\" Type=\"Edm.String\" /><Property Name=\"ShipCountry\" Type=\"Edm.String\" /><P" +
                "roperty Name=\"ShipName\" Type=\"Edm.String\" /><Property Name=\"ShippedDate\" Type=\"E" +
                "dm.DateTime\" /><Property Name=\"ShipPostalCode\" Type=\"Edm.String\" /><Property Nam" +
                "e=\"ShipRegion\" Type=\"Edm.String\" /><Property Name=\"ShipVia\" Type=\"Edm.Int32\" /><" +
                "NavigationProperty Name=\"OrderDetails\" Relationship=\"Northwind.DAL.EntityClasses" +
                ".OrderEntity_OrderDetails_OrderDetailEntity_Order\" ToRole=\"";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "OrderDetailEntity_Order\" FromRole=\"OrderEntity_OrderDetails\" /><NavigationPropert" +
                "y Name=\"Customer\" Relationship=\"Northwind.DAL.EntityClasses.CustomerEntity_Order" +
                "s_OrderEntity_Customer\" ToRole=\"CustomerEntity_Orders\" FromRole=\"OrderEntity_Cus" +
                "tomer\" /><NavigationProperty Name=\"Employee\" Relationship=\"Northwind.DAL.EntityC" +
                "lasses.EmployeeEntity_Orders_OrderEntity_Employee\" ToRole=\"EmployeeEntity_Orders" +
                "\" FromRole=\"OrderEntity_Employee\" /><NavigationProperty Name=\"Shipper\" Relations" +
                "hip=\"Northwind.DAL.EntityClasses.OrderEntity_Shipper_ShipperEntity_Orders\" ToRol" +
                "e=\"ShipperEntity_Orders\" FromRole=\"OrderEntity_Shipper\" /></EntityType><EntityTy" +
                "pe Name=\"OrderDetailEntity\"><Key><PropertyRef Name=\"OrderId\" /><PropertyRef Name" +
                "=\"ProductId\" /></Key><Property Name=\"Discount\" Type=\"Edm.Single\" Nullable=\"false" +
                "\" /><Property Name=\"OrderId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=" +
                "\"ProductId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Quantity\" Type=\"" +
                "Edm.Int16\" Nullable=\"false\" /><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" Null" +
                "able=\"false\" /><NavigationProperty Name=\"Order\" Relationship=\"Northwind.DAL.Enti" +
                "tyClasses.OrderEntity_OrderDetails_OrderDetailEntity_Order\" ToRole=\"OrderEntity_" +
                "OrderDetails\" FromRole=\"OrderDetailEntity_Order\" /><NavigationProperty Name=\"Pro" +
                "duct\" Relationship=\"Northwind.DAL.EntityClasses.OrderDetailEntity_Product_Produc" +
                "tEntity_OrderDetails\" ToRole=\"ProductEntity_OrderDetails\" FromRole=\"OrderDetailE" +
                "ntity_Product\" /></EntityType><EntityType Name=\"ProductEntity\"><Key><PropertyRef" +
                " Name=\"ProductId\" /></Key><Property Name=\"CategoryId\" Type=\"Edm.Int32\" /><Proper" +
                "ty Name=\"Discontinued\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Pro" +
                "ductId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ProductName\" Type=\"E" +
                "dm.String\" /><Property Name=\"QuantityPerUnit\" Type=\"Edm.String\" /><Property Name" +
                "=\"ReorderLevel\" Type=\"Edm.Int16\" /><Property Name=\"SupplierId\" Type=\"Edm.Int32\" " +
                "/><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" /><Property Name=\"UnitsInStock\" " +
                "Type=\"Edm.Int16\" /><Property Name=\"UnitsOnOrder\" Type=\"Edm.Int16\" /><NavigationP" +
                "roperty Name=\"OrderDetails\" Relationship=\"Northwind.DAL.EntityClasses.OrderDetai" +
                "lEntity_Product_ProductEntity_OrderDetails\" ToRole=\"OrderDetailEntity_Product\" F" +
                "romRole=\"ProductEntity_OrderDetails\" /><NavigationProperty Name=\"Category\" Relat" +
                "ionship=\"Northwind.DAL.EntityClasses.CategoryEntity_Products_ProductEntity_Categ" +
                "ory\" ToRole=\"CategoryEntity_Products\" FromRole=\"ProductEntity_Category\" /><Navig" +
                "ationProperty Name=\"Supplier\" Relationship=\"Northwind.DAL.EntityClasses.ProductE" +
                "ntity_Supplier_SupplierEntity_Products\" ToRole=\"SupplierEntity_Products\" FromRol" +
                "e=\"ProductEntity_Supplier\" /></EntityType><EntityType Name=\"RegionEntity\"><Key><" +
                "PropertyRef Name=\"RegionId\" /></Key><Property Name=\"RegionDescription\" Type=\"Edm" +
                ".String\" /><Property Name=\"RegionId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Naviga" +
                "tionProperty Name=\"Territories\" Relationship=\"Northwind.DAL.EntityClasses.Region" +
                "Entity_Territories_TerritoryEntity_Region\" ToRole=\"TerritoryEntity_Region\" FromR" +
                "ole=\"RegionEntity_Territories\" /></EntityType><EntityType Name=\"ShipperEntity\"><" +
                "Key><PropertyRef Name=\"ShipperId\" /></Key><Property Name=\"CompanyName\" Type=\"Edm" +
                ".String\" /><Property Name=\"Phone\" Type=\"Edm.String\" /><Property Name=\"ShipperId\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Orders\" Relations" +
                "hip=\"Northwind.DAL.EntityClasses.OrderEntity_Shipper_ShipperEntity_Orders\" ToRol" +
                "e=\"OrderEntity_Shipper\" FromRole=\"ShipperEntity_Orders\" /></EntityType><EntityTy" +
                "pe Name=\"SupplierEntity\"><Key><PropertyRef Name=\"SupplierId\" /></Key><Property N" +
                "ame=\"Address\" Type=\"Edm.String\" /><Property Name=\"City\" Type=\"Edm.String\" /><Pro" +
                "perty Name=\"CompanyName\" Type=\"Edm.String\" /><Property Name=\"ContactName\" Type=\"" +
                "Edm.String\" /><Property Name=\"ContactTitle\" Type=\"Edm.String\" /><Property Name=\"" +
                "Country\" Type=\"Edm.String\" /><Property Name=\"Fax\" Type=\"Edm.String\" /><Property " +
                "Name=\"HomePage\" Type=\"Edm.String\" /><Property Name=\"Phone\" Type=\"Edm.String\" /><" +
                "Property Name=\"PostalCode\" Type=\"Edm.String\" /><Property Name=\"Region\" Type=\"Edm" +
                ".String\" /><Property Name=\"SupplierId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Navi" +
                "gationProperty Name=\"Products\" Relationship=\"Northwind.DAL.EntityClasses.Product" +
                "Entity_Supplier_SupplierEntity_Products\" ToRole=\"ProductEntity_Supplier\" FromRol" +
                "e=\"SupplierEntity_Products\" /></EntityType><EntityType Name=\"TerritoryEntity\"><K" +
                "ey><PropertyRef Name=\"TerritoryId\" /></Key><Property Name=\"RegionId\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><Property Name=\"TerritoryDescription\" Type=\"Edm.String\"" +
                " /><Property Name=\"TerritoryId\" Type=\"Edm.String\" Nullable=\"false\" /><Navigation" +
                "Property Name=\"EmployeeTerritories\" Relationship=\"Northwind.DAL.EntityClasses.Em" +
                "ployeeTerritoryEntity_Territory_TerritoryEntity_EmployeeTerritories\" ToRole=\"Emp" +
                "loyeeTerritoryEntity_Territory\" FromRole=\"TerritoryEntity_EmployeeTerritories\" /" +
                "><NavigationProperty Name=\"Employees\" Relationship=\"Northwind.DAL.EntityClasses." +
                "TerritoryEntity_Employees\" ToRole=\"Employees\" FromRole=\"TerritoryEntity\" /><Navi" +
                "gationProperty Name=\"Region\" Relationship=\"Northwind.DAL.EntityClasses.RegionEnt" +
                "ity_Territories_TerritoryEntity_Region\" ToRole=\"RegionEntity_Territories\" FromRo" +
                "le=\"TerritoryEntity_Region\" /></EntityType><Association Name=\"CategoryEntity_Pro" +
                "ducts_ProductEntity_Category\"><End Type=\"Northwind.DAL.EntityClasses.ProductEnti" +
                "ty\" Role=\"ProductEntity_Category\" Multiplicity=\"*\" /><End Type=\"Northwind.DAL.En" +
                "tityClasses.CategoryEntity\" Role=\"CategoryEntity_Products\" Multiplicity=\"0..1\" /" +
                "></Association><Association Name=\"CustomerEntity_CustomerCustomerDemos_CustomerC" +
                "ustomerDemoEntity_Customer\"><End Type=\"Northwind.DAL.EntityClasses.CustomerCusto" +
                "merDemoEntity\" Role=\"CustomerCustomerDemoEntity_Customer\" Multiplicity=\"*\" /><En" +
                "d Type=\"Northwind.DAL.EntityClasses.CustomerEntity\" Role=\"CustomerEntity_Custome" +
                "rCustomerDemos\" Multiplicity=\"0..1\" /></Association><Association Name=\"CustomerE" +
                "ntity_Orders_OrderEntity_Customer\"><End Type=\"Northwind.DAL.EntityClasses.OrderE" +
                "ntity\" Role=\"OrderEntity_Customer\" Multiplicity=\"*\" /><End Type=\"Northwind.DAL.E" +
                "ntityClasses.CustomerEntity\" Role=\"CustomerEntity_Orders\" Multiplicity=\"0..1\" />" +
                "</Association><Association Name=\"CustomerEntity_CustomerDemographics\"><End Type=" +
                "\"Northwind.DAL.EntityClasses.CustomerEntity\" Role=\"CustomerEntity\" Multiplicity=" +
                "\"*\" /><End Type=\"Northwind.DAL.EntityClasses.CustomerDemographicEntity\" Role=\"Cu" +
                "stomerDemographics\" Multiplicity=\"*\" /></Association><Association Name=\"Customer" +
                "Entity_EmployeesViaOrders\"><End Type=\"Northwind.DAL.EntityClasses.EmployeeEntity" +
                "\" Role=\"EmployeesViaOrders\" Multiplicity=\"*\" /><End Type=\"Northwind.DAL.EntityCl" +
                "asses.CustomerEntity\" Role=\"CustomerEntity\" Multiplicity=\"*\" /></Association><As" +
                "sociation Name=\"CustomerCustomerDemoEntity_CustomerDemographic_CustomerDemograph" +
                "icEntity_CustomerCustomerDemos\"><End Type=\"Northwind.DAL.EntityClasses.CustomerD" +
                "emographicEntity\" Role=\"CustomerDemographicEntity_CustomerCustomerDemos\" Multipl" +
                "icity=\"0..1\" /><End Type=\"Northwind.DAL.EntityClasses.CustomerCustomerDemoEntity" +
                "\" Role=\"CustomerCustomerDemoEntity_CustomerDemographic\" Multiplicity=\"*\" /></Ass" +
                "ociation><Association Name=\"CustomerDemographicEntity_Customers\"><End Type=\"Nort" +
                "hwind.DAL.EntityClasses.CustomerEntity\" Role=\"Customers\" Multiplicity=\"*\" /><End" +
                " Type=\"Northwind.DAL.EntityClasses.CustomerDemographicEntity\" Role=\"CustomerDemo" +
                "graphicEntity\" Multiplicity=\"*\" /></Association><Association Name=\"EmployeeEntit" +
                "y_Staff_EmployeeEntity_Manager\"><End Type=\"Northwind.DAL.En";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart2 = "tityClasses.EmployeeEntity\" Role=\"EmployeeEntity_Manager\" Multiplicity=\"*\" /><End" +
                " Type=\"Northwind.DAL.EntityClasses.EmployeeEntity\" Role=\"EmployeeEntity_Staff\" M" +
                "ultiplicity=\"0..1\" /></Association><Association Name=\"EmployeeEntity_EmployeeTer" +
                "ritories_EmployeeTerritoryEntity_Employee\"><End Type=\"Northwind.DAL.EntityClasse" +
                "s.EmployeeTerritoryEntity\" Role=\"EmployeeTerritoryEntity_Employee\" Multiplicity=" +
                "\"*\" /><End Type=\"Northwind.DAL.EntityClasses.EmployeeEntity\" Role=\"EmployeeEntit" +
                "y_EmployeeTerritories\" Multiplicity=\"0..1\" /></Association><Association Name=\"Em" +
                "ployeeEntity_Orders_OrderEntity_Employee\"><End Type=\"Northwind.DAL.EntityClasses" +
                ".OrderEntity\" Role=\"OrderEntity_Employee\" Multiplicity=\"*\" /><End Type=\"Northwin" +
                "d.DAL.EntityClasses.EmployeeEntity\" Role=\"EmployeeEntity_Orders\" Multiplicity=\"0" +
                "..1\" /></Association><Association Name=\"EmployeeEntity_CustomersViaOrders\"><End " +
                "Type=\"Northwind.DAL.EntityClasses.EmployeeEntity\" Role=\"EmployeeEntity\" Multipli" +
                "city=\"*\" /><End Type=\"Northwind.DAL.EntityClasses.CustomerEntity\" Role=\"Customer" +
                "sViaOrders\" Multiplicity=\"*\" /></Association><Association Name=\"EmployeeEntity_T" +
                "erritories\"><End Type=\"Northwind.DAL.EntityClasses.TerritoryEntity\" Role=\"Territ" +
                "ories\" Multiplicity=\"*\" /><End Type=\"Northwind.DAL.EntityClasses.EmployeeEntity\"" +
                " Role=\"EmployeeEntity\" Multiplicity=\"*\" /></Association><Association Name=\"Emplo" +
                "yeeTerritoryEntity_Territory_TerritoryEntity_EmployeeTerritories\"><End Type=\"Nor" +
                "thwind.DAL.EntityClasses.TerritoryEntity\" Role=\"TerritoryEntity_EmployeeTerritor" +
                "ies\" Multiplicity=\"0..1\" /><End Type=\"Northwind.DAL.EntityClasses.EmployeeTerrit" +
                "oryEntity\" Role=\"EmployeeTerritoryEntity_Territory\" Multiplicity=\"*\" /></Associa" +
                "tion><Association Name=\"OrderEntity_OrderDetails_OrderDetailEntity_Order\"><End T" +
                "ype=\"Northwind.DAL.EntityClasses.OrderDetailEntity\" Role=\"OrderDetailEntity_Orde" +
                "r\" Multiplicity=\"*\" /><End Type=\"Northwind.DAL.EntityClasses.OrderEntity\" Role=\"" +
                "OrderEntity_OrderDetails\" Multiplicity=\"0..1\" /></Association><Association Name=" +
                "\"OrderEntity_Shipper_ShipperEntity_Orders\"><End Type=\"Northwind.DAL.EntityClasse" +
                "s.ShipperEntity\" Role=\"ShipperEntity_Orders\" Multiplicity=\"0..1\" /><End Type=\"No" +
                "rthwind.DAL.EntityClasses.OrderEntity\" Role=\"OrderEntity_Shipper\" Multiplicity=\"" +
                "*\" /></Association><Association Name=\"OrderDetailEntity_Product_ProductEntity_Or" +
                "derDetails\"><End Type=\"Northwind.DAL.EntityClasses.ProductEntity\" Role=\"ProductE" +
                "ntity_OrderDetails\" Multiplicity=\"0..1\" /><End Type=\"Northwind.DAL.EntityClasses" +
                ".OrderDetailEntity\" Role=\"OrderDetailEntity_Product\" Multiplicity=\"*\" /></Associ" +
                "ation><Association Name=\"ProductEntity_Supplier_SupplierEntity_Products\"><End Ty" +
                "pe=\"Northwind.DAL.EntityClasses.SupplierEntity\" Role=\"SupplierEntity_Products\" M" +
                "ultiplicity=\"0..1\" /><End Type=\"Northwind.DAL.EntityClasses.ProductEntity\" Role=" +
                "\"ProductEntity_Supplier\" Multiplicity=\"*\" /></Association><Association Name=\"Reg" +
                "ionEntity_Territories_TerritoryEntity_Region\"><End Type=\"Northwind.DAL.EntityCla" +
                "sses.TerritoryEntity\" Role=\"TerritoryEntity_Region\" Multiplicity=\"*\" /><End Type" +
                "=\"Northwind.DAL.EntityClasses.RegionEntity\" Role=\"RegionEntity_Territories\" Mult" +
                "iplicity=\"0..1\" /></Association><Association Name=\"TerritoryEntity_Employees\"><E" +
                "nd Type=\"Northwind.DAL.EntityClasses.TerritoryEntity\" Role=\"TerritoryEntity\" Mul" +
                "tiplicity=\"*\" /><End Type=\"Northwind.DAL.EntityClasses.EmployeeEntity\" Role=\"Emp" +
                "loyees\" Multiplicity=\"*\" /></Association><EntityContainer Name=\"LLBLGenProODataS" +
                "ervice\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Category\" EntityType=" +
                "\"Northwind.DAL.EntityClasses.CategoryEntity\" /><EntitySet Name=\"Customer\" Entity" +
                "Type=\"Northwind.DAL.EntityClasses.CustomerEntity\" /><EntitySet Name=\"CustomerCus" +
                "tomerDemo\" EntityType=\"Northwind.DAL.EntityClasses.CustomerCustomerDemoEntity\" /" +
                "><EntitySet Name=\"CustomerDemographic\" EntityType=\"Northwind.DAL.EntityClasses.C" +
                "ustomerDemographicEntity\" /><EntitySet Name=\"Employee\" EntityType=\"Northwind.DAL" +
                ".EntityClasses.EmployeeEntity\" /><EntitySet Name=\"EmployeeTerritory\" EntityType=" +
                "\"Northwind.DAL.EntityClasses.EmployeeTerritoryEntity\" /><EntitySet Name=\"Order\" " +
                "EntityType=\"Northwind.DAL.EntityClasses.OrderEntity\" /><EntitySet Name=\"OrderDet" +
                "ail\" EntityType=\"Northwind.DAL.EntityClasses.OrderDetailEntity\" /><EntitySet Nam" +
                "e=\"Product\" EntityType=\"Northwind.DAL.EntityClasses.ProductEntity\" /><EntitySet " +
                "Name=\"Region\" EntityType=\"Northwind.DAL.EntityClasses.RegionEntity\" /><EntitySet" +
                " Name=\"Shipper\" EntityType=\"Northwind.DAL.EntityClasses.ShipperEntity\" /><Entity" +
                "Set Name=\"Supplier\" EntityType=\"Northwind.DAL.EntityClasses.SupplierEntity\" /><E" +
                "ntitySet Name=\"Territory\" EntityType=\"Northwind.DAL.EntityClasses.TerritoryEntit" +
                "y\" /><AssociationSet Name=\"CategoryEntityProductEntityCategoryId\" Association=\"N" +
                "orthwind.DAL.EntityClasses.CategoryEntity_Products_ProductEntity_Category\"><End " +
                "Role=\"CategoryEntity_Products\" EntitySet=\"Category\" /><End Role=\"ProductEntity_C" +
                "ategory\" EntitySet=\"Product\" /></AssociationSet><AssociationSet Name=\"CustomerEn" +
                "tityCustomerCustomerDemoEntityCustomerId\" Association=\"Northwind.DAL.EntityClass" +
                "es.CustomerEntity_CustomerCustomerDemos_CustomerCustomerDemoEntity_Customer\"><En" +
                "d Role=\"CustomerEntity_CustomerCustomerDemos\" EntitySet=\"Customer\" /><End Role=\"" +
                "CustomerCustomerDemoEntity_Customer\" EntitySet=\"CustomerCustomerDemo\" /></Associ" +
                "ationSet><AssociationSet Name=\"CustomerEntityOrderEntityCustomerId\" Association=" +
                "\"Northwind.DAL.EntityClasses.CustomerEntity_Orders_OrderEntity_Customer\"><End Ro" +
                "le=\"CustomerEntity_Orders\" EntitySet=\"Customer\" /><End Role=\"OrderEntity_Custome" +
                "r\" EntitySet=\"Order\" /></AssociationSet><AssociationSet Name=\"CustomerEntity_Cus" +
                "tomerDemographics\" Association=\"Northwind.DAL.EntityClasses.CustomerEntity_Custo" +
                "merDemographics\"><End Role=\"CustomerEntity\" EntitySet=\"Customer\" /><End Role=\"Cu" +
                "stomerDemographics\" EntitySet=\"CustomerDemographic\" /></AssociationSet><Associat" +
                "ionSet Name=\"CustomerEntity_EmployeesViaOrders\" Association=\"Northwind.DAL.Entit" +
                "yClasses.CustomerEntity_EmployeesViaOrders\"><End Role=\"CustomerEntity\" EntitySet" +
                "=\"Customer\" /><End Role=\"EmployeesViaOrders\" EntitySet=\"Employee\" /></Associatio" +
                "nSet><AssociationSet Name=\"CustomerDemographicEntityCustomerCustomerDemoEntityCu" +
                "stomerTypeId\" Association=\"Northwind.DAL.EntityClasses.CustomerCustomerDemoEntit" +
                "y_CustomerDemographic_CustomerDemographicEntity_CustomerCustomerDemos\"><End Role" +
                "=\"CustomerCustomerDemoEntity_CustomerDemographic\" EntitySet=\"CustomerCustomerDem" +
                "o\" /><End Role=\"CustomerDemographicEntity_CustomerCustomerDemos\" EntitySet=\"Cust" +
                "omerDemographic\" /></AssociationSet><AssociationSet Name=\"CustomerDemographicEnt" +
                "ity_Customers\" Association=\"Northwind.DAL.EntityClasses.CustomerDemographicEntit" +
                "y_Customers\"><End Role=\"CustomerDemographicEntity\" EntitySet=\"CustomerDemographi" +
                "c\" /><End Role=\"Customers\" EntitySet=\"Customer\" /></AssociationSet><AssociationS" +
                "et Name=\"EmployeeEntityEmployeeEntityReportsTo\" Association=\"Northwind.DAL.Entit" +
                "yClasses.EmployeeEntity_Staff_EmployeeEntity_Manager\"><End Role=\"EmployeeEntity_" +
                "Staff\" EntitySet=\"Employee\" /><End Role=\"EmployeeEntity_Manager\" EntitySet=\"Empl" +
                "oyee\" /></AssociationSet><AssociationSet Name=\"EmployeeEntityEmployeeTerritoryEn" +
                "tityEmployeeId\" Association=\"Northwind.DAL.EntityClasses.EmployeeEntity_Employee" +
                "Territories_EmployeeTerritoryEntity_Employee\"><End Role=\"EmployeeEntity_Employee" +
                "Territories\" EntitySet=\"Employee\" /><End Role=\"EmployeeTerritoryEntity_Employee\"" +
                " EntitySet=\"EmployeeTerritory\" /></AssociationSet><AssociationSet Name=\"Employee" +
                "EntityOrderEntityEmployeeId\" Association=\"Northwind.DAL.Ent";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart3 = "ityClasses.EmployeeEntity_Orders_OrderEntity_Employee\"><End Role=\"EmployeeEntity_" +
                "Orders\" EntitySet=\"Employee\" /><End Role=\"OrderEntity_Employee\" EntitySet=\"Order" +
                "\" /></AssociationSet><AssociationSet Name=\"EmployeeEntity_CustomersViaOrders\" As" +
                "sociation=\"Northwind.DAL.EntityClasses.EmployeeEntity_CustomersViaOrders\"><End R" +
                "ole=\"EmployeeEntity\" EntitySet=\"Employee\" /><End Role=\"CustomersViaOrders\" Entit" +
                "ySet=\"Customer\" /></AssociationSet><AssociationSet Name=\"EmployeeEntity_Territor" +
                "ies\" Association=\"Northwind.DAL.EntityClasses.EmployeeEntity_Territories\"><End R" +
                "ole=\"EmployeeEntity\" EntitySet=\"Employee\" /><End Role=\"Territories\" EntitySet=\"T" +
                "erritory\" /></AssociationSet><AssociationSet Name=\"TerritoryEntityEmployeeTerrit" +
                "oryEntityTerritoryId\" Association=\"Northwind.DAL.EntityClasses.EmployeeTerritory" +
                "Entity_Territory_TerritoryEntity_EmployeeTerritories\"><End Role=\"EmployeeTerrito" +
                "ryEntity_Territory\" EntitySet=\"EmployeeTerritory\" /><End Role=\"TerritoryEntity_E" +
                "mployeeTerritories\" EntitySet=\"Territory\" /></AssociationSet><AssociationSet Nam" +
                "e=\"OrderEntityOrderDetailEntityOrderId\" Association=\"Northwind.DAL.EntityClasses" +
                ".OrderEntity_OrderDetails_OrderDetailEntity_Order\"><End Role=\"OrderEntity_OrderD" +
                "etails\" EntitySet=\"Order\" /><End Role=\"OrderDetailEntity_Order\" EntitySet=\"Order" +
                "Detail\" /></AssociationSet><AssociationSet Name=\"ShipperEntityOrderEntityShipVia" +
                "\" Association=\"Northwind.DAL.EntityClasses.OrderEntity_Shipper_ShipperEntity_Ord" +
                "ers\"><End Role=\"OrderEntity_Shipper\" EntitySet=\"Order\" /><End Role=\"ShipperEntit" +
                "y_Orders\" EntitySet=\"Shipper\" /></AssociationSet><AssociationSet Name=\"ProductEn" +
                "tityOrderDetailEntityProductId\" Association=\"Northwind.DAL.EntityClasses.OrderDe" +
                "tailEntity_Product_ProductEntity_OrderDetails\"><End Role=\"OrderDetailEntity_Prod" +
                "uct\" EntitySet=\"OrderDetail\" /><End Role=\"ProductEntity_OrderDetails\" EntitySet=" +
                "\"Product\" /></AssociationSet><AssociationSet Name=\"SupplierEntityProductEntitySu" +
                "pplierId\" Association=\"Northwind.DAL.EntityClasses.ProductEntity_Supplier_Suppli" +
                "erEntity_Products\"><End Role=\"ProductEntity_Supplier\" EntitySet=\"Product\" /><End" +
                " Role=\"SupplierEntity_Products\" EntitySet=\"Supplier\" /></AssociationSet><Associa" +
                "tionSet Name=\"RegionEntityTerritoryEntityRegionId\" Association=\"Northwind.DAL.En" +
                "tityClasses.RegionEntity_Territories_TerritoryEntity_Region\"><End Role=\"RegionEn" +
                "tity_Territories\" EntitySet=\"Region\" /><End Role=\"TerritoryEntity_Region\" Entity" +
                "Set=\"Territory\" /></AssociationSet><AssociationSet Name=\"TerritoryEntity_Employe" +
                "es\" Association=\"Northwind.DAL.EntityClasses.TerritoryEntity_Employees\"><End Rol" +
                "e=\"TerritoryEntity\" EntitySet=\"Territory\" /><End Role=\"Employees\" EntitySet=\"Emp" +
                "loyee\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:" +
                "Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1, ModelPart2, ModelPart3);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
  
    
}
