///////////////////////////////////////////////////////////////
// This is generated code. If you modify this code, be aware
// of the fact that when you re-generate the code, your changes
// are lost. If you want to keep your changes, make this file read-only
// when you have finished your changes, however it is recommended that
// you inherit from this class to extend the functionality of this generated
// class or you modify / extend the templates used to generate this code.
//////////////////////////////////////////////////////////////
// Code is generated using LLBLGen Pro version: 1.0.2005.1
// Code is generated on: Wednesday, November 09, 2005 8:47:29 PM
// Code is generated using templates: C# template set for SqlServer (1.0.2005.1)
// Templates vendor: Solutions Design.
// Templates version: 1.0.2005.1.102305
//////////////////////////////////////////////////////////////
using System;
using System.Data;
using AW.Data;
using AW.Data.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace AW.Data.FactoryClasses
{
	/// <summary>
	/// Generates IEntityFields instances for different kind of Entities. 
	/// This class is generated. Do not modify.
	/// </summary>
	public class EntityFieldsFactory
	{
		/// <summary>
		/// Private CTor, no instantiation possible.
		/// </summary>
		private EntityFieldsFactory()
		{
		}


		/// <summary>General factory entrance method which will return an EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedEntityType">The type of entity the fields are for</param>
		/// <returns>The IEntityFields instance requested</returns>
		public static IEntityFields CreateEntityFieldsObject(EntityType relatedEntityType)
		{
			IEntityFields fieldsToReturn=null;
			switch(relatedEntityType)
			{
				case AW.Data.EntityType.AddressEntity:
					fieldsToReturn = CreateAddressEntityFields();
					break;
				case AW.Data.EntityType.AddressTypeEntity:
					fieldsToReturn = CreateAddressTypeEntityFields();
					break;
				case AW.Data.EntityType.ContactEntity:
					fieldsToReturn = CreateContactEntityFields();
					break;
				case AW.Data.EntityType.CountryRegionEntity:
					fieldsToReturn = CreateCountryRegionEntityFields();
					break;
				case AW.Data.EntityType.CustomerEntity:
					fieldsToReturn = CreateCustomerEntityFields();
					break;
				case AW.Data.EntityType.CustomerAddressEntity:
					fieldsToReturn = CreateCustomerAddressEntityFields();
					break;
				case AW.Data.EntityType.CustomerViewRelatedEntity:
					fieldsToReturn = CreateCustomerViewRelatedEntityFields();
					break;
				case AW.Data.EntityType.EmployeeEntity:
					fieldsToReturn = CreateEmployeeEntityFields();
					break;
				case AW.Data.EntityType.EmployeeAddressEntity:
					fieldsToReturn = CreateEmployeeAddressEntityFields();
					break;
				case AW.Data.EntityType.IndividualEntity:
					fieldsToReturn = CreateIndividualEntityFields();
					break;
				case AW.Data.EntityType.ProductEntity:
					fieldsToReturn = CreateProductEntityFields();
					break;
				case AW.Data.EntityType.SalesOrderDetailEntity:
					fieldsToReturn = CreateSalesOrderDetailEntityFields();
					break;
				case AW.Data.EntityType.SalesOrderHeaderEntity:
					fieldsToReturn = CreateSalesOrderHeaderEntityFields();
					break;
				case AW.Data.EntityType.ShipMethodEntity:
					fieldsToReturn = CreateShipMethodEntityFields();
					break;
				case AW.Data.EntityType.SpecialOfferEntity:
					fieldsToReturn = CreateSpecialOfferEntityFields();
					break;
				case AW.Data.EntityType.SpecialOfferProductEntity:
					fieldsToReturn = CreateSpecialOfferProductEntityFields();
					break;
				case AW.Data.EntityType.StateProvinceEntity:
					fieldsToReturn = CreateStateProvinceEntityFields();
					break;
			}
			return fieldsToReturn;
		}
		
		/// <summary>General method which will return an array of IEntityFieldCore objects, used by the InheritanceInfoProvider. Only the fields defined in the entity are returned, no inherited fields.</summary>
		/// <param name="entityName">the name of the entity to get the fields for. Example: "CustomerEntity"</param>
		/// <returns>array of IEntityFieldCore fields, defined in the entity with the name specified</returns>
		internal static IEntityFieldCore[] CreateFields(string entityName)
		{
			IEntityFieldCore[] toReturn = null;
			switch(entityName)
			{
				default:
					break;
			}
			return toReturn;
		}

		/// <summary>General factory entrance method which will return a TypedView EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedTypedViewType">The type of typed view the fields are for</param>
		/// <returns>The IEntityFields instance requested</returns>
		public static IEntityFields CreateTypedViewEntityFieldsObject(TypedViewType relatedTypedViewType)
		{
			IEntityFields fieldsToReturn=null;
			switch(relatedTypedViewType)
			{
				case TypedViewType.CustomerViewTypedView:
					fieldsToReturn = CreateCustomerViewTypedViewEntityFields();
					break;
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the AddressEntity.</summary>
		private static IEntityFields CreateAddressEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)AddressFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)AddressFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((AddressFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the AddressTypeEntity.</summary>
		private static IEntityFields CreateAddressTypeEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)AddressTypeFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)AddressTypeFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((AddressTypeFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the ContactEntity.</summary>
		private static IEntityFields CreateContactEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)ContactFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)ContactFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ContactFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the CountryRegionEntity.</summary>
		private static IEntityFields CreateCountryRegionEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)CountryRegionFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)CountryRegionFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CountryRegionFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the CustomerEntity.</summary>
		private static IEntityFields CreateCustomerEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)CustomerFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)CustomerFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CustomerFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the CustomerAddressEntity.</summary>
		private static IEntityFields CreateCustomerAddressEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)CustomerAddressFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)CustomerAddressFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CustomerAddressFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the CustomerViewRelatedEntity.</summary>
		private static IEntityFields CreateCustomerViewRelatedEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)CustomerViewRelatedFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)CustomerViewRelatedFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CustomerViewRelatedFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the EmployeeEntity.</summary>
		private static IEntityFields CreateEmployeeEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)EmployeeFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)EmployeeFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((EmployeeFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the EmployeeAddressEntity.</summary>
		private static IEntityFields CreateEmployeeAddressEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)EmployeeAddressFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)EmployeeAddressFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((EmployeeAddressFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the IndividualEntity.</summary>
		private static IEntityFields CreateIndividualEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)IndividualFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)IndividualFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((IndividualFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the ProductEntity.</summary>
		private static IEntityFields CreateProductEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)ProductFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)ProductFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ProductFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the SalesOrderDetailEntity.</summary>
		private static IEntityFields CreateSalesOrderDetailEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)SalesOrderDetailFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)SalesOrderDetailFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((SalesOrderDetailFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the SalesOrderHeaderEntity.</summary>
		private static IEntityFields CreateSalesOrderHeaderEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)SalesOrderHeaderFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)SalesOrderHeaderFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((SalesOrderHeaderFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the ShipMethodEntity.</summary>
		private static IEntityFields CreateShipMethodEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)ShipMethodFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)ShipMethodFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ShipMethodFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the SpecialOfferEntity.</summary>
		private static IEntityFields CreateSpecialOfferEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)SpecialOfferFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)SpecialOfferFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((SpecialOfferFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the SpecialOfferProductEntity.</summary>
		private static IEntityFields CreateSpecialOfferProductEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)SpecialOfferProductFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)SpecialOfferProductFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((SpecialOfferProductFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the StateProvinceEntity.</summary>
		private static IEntityFields CreateStateProvinceEntityFields()
		{

			IEntityFields fieldsToReturn = new EntityFields((int)StateProvinceFieldIndex.AmountOfFields, InheritanceInfoProviderSingleton.GetInstance());
			for(int i=0;i<(int)StateProvinceFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((StateProvinceFieldIndex)i);
			}
			return fieldsToReturn;
		}
	

		/// <summary>Creates a complete EntityFields instance for the CustomerViewEntity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateCustomerViewTypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)CustomerViewFieldIndex.AmountOfFields, null);
			for(int i=0;i<(int)CustomerViewFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CustomerViewFieldIndex)i);
			}
			return fieldsToReturn;
		}

		#region Included Code

		#endregion
	}
}
